# Generated by Django 5.0.1 on 2024-02-06 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityBranchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('01_ВПФ', 'Владимирский'), ('02_КРФ', 'Кировский'), ('03_КОФ', 'Коми'), ('04_МЧФ', 'Марий Эл и Чувашии'), ('05_МРФ', 'Мордовский'), ('06_НГФ', 'Нижегородский'), ('07_ОРФ', 'Оренбургский'), ('08_ПМФ', 'Пермский'), ('09_СМФ', 'Самара'), ('10_СРФ', 'Саратовский'), ('11_СВФ', 'Свердловский'), ('12_УДФ', 'Удмуртский'), ('13_УЛФ', 'Ульяновский'), ('14_ПНФ', 'Пензенский')], max_length=6)),
                ('field1', models.IntegerField(default=0)),
                ('field2', models.IntegerField(default=0)),
                ('field3', models.IntegerField(default=0)),
                ('field4', models.IntegerField(default=0)),
                ('field5', models.IntegerField(default=0)),
                ('field6', models.IntegerField(default=0)),
                ('field7', models.IntegerField(default=0)),
                ('field8', models.IntegerField(default=0)),
                ('field9', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
